name: Linux and macOS CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntuBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: apt-update
      run: sudo apt-get update -qq
    - name: apt get qt
      run: sudo apt-get install -y --no-install-recommends qtdeclarative5-dev libqt5svg5-dev qml-module-qtgraphicaleffects qml-module-qtquick-layouts qml-module-qtquick-dialogs qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings libqt5websockets5-dev qtmultimedia5-dev libqt5multimedia5-plugins qml-module-qtmultimedia qtquickcontrols2-5-dev libvlccore-dev libvlc-dev
    - name: run qmake
      run: qmake -makefile -o src/Makefile src/AniLibria.pro
    - name: run make
      run: make -j2 -C src
#    - name: copy to deb package
#      run: mkdir specs/deb/tmp1/usr/bin; cp src/AniLibria specs/deb/tmp1/usr/bin
#    - name: build deb package
#      run: dpkg-deb -b specs/deb/tmp1 anilibria_amd64.deb
#    - uses: actions/upload-artifact@v3
#      with:
#        name: deb-package
#        path: anilibria_amd64.deb      
  macosbuild:
    runs-on: macos-12    
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt dependencies
      uses: jurplel/install-qt-action@v3
      with:
        version: 5.15.2
        target: 'desktop'
        arch: 'clang_64'        
    - name: run qmake
      run: qmake -makefile -o src/Makefile src/AniLibria.pro
    - name: run make
      run: make -j2 -C src

