name: Linux and macOS CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntuBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: apt-update
      run: sudo apt-get update -qq
    - name: apt get qt
      run: sudo apt-get install -y --no-install-recommends qtdeclarative5-dev libqt5svg5-dev qml-module-qtgraphicaleffects qml-module-qtquick-layouts qml-module-qtquick-dialogs qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings libqt5websockets5-dev qtmultimedia5-dev libqt5multimedia5-plugins qml-module-qtmultimedia qtquickcontrols2-5-dev libvlccore-dev libvlc-dev libmpv-dev pkg-config
    - name: run qmake
      run: qmake -makefile -o src/Makefile src/AniLibria.pro CONFIG+=unixvlc CONFIG+=unixmpv
    - name: run make
      run: make -j2 -C src
  macosbuild:
    runs-on: macos-12    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: run qmake
      run: brew install pkg-config
    - name: Install Qt dependencies
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version: 5.15.2
        target: 'desktop'
        arch: 'clang_64'        
    - name: run qmake
      run: qmake -makefile -o src/Makefile src/AniLibria.pro
    - name: run make
      run: make -j2 -C src

